ajout route export + tableau historique des demandes de contrat
anct-cnum/api-admin-conseillers-numerique pull request #152
Opened 2023-04-25 09:28 UTC by QuentinFontenay

2023-05-04 10:06 UTC, squirrion commented on src/services/exports/controllers/getExportHistoriqueContratsCsv.ts
> +        'renouvelee',
hum je ne sais pas ici : on ne gère pas de statut autre que finalisee quand y a un contrat , ca peut avoir des conséquences dans les contrôles un peu partout.
Je ne sais pas ce qui va être fait entre CDI & CDD (dédoublonnement si CDD mais l'ancien contrat sera une fin qui était en lien avec une fin naturelle" et CDI rien du tout ca continu non ?

2023-05-04 10:09 UTC, squirrion commented on src/services/exports/controllers/getExportHistoriqueContratsCsv.ts
> +              emetteurRenouvellement: 1, // à définir
oui pk pas si on stocke date faudra stocker qui comme pour emetteurRupture je crois

2023-05-04 10:11 UTC, squirrion commented on src/services/exports/exports.repository.ts
> +            contrat?.statut ?? 'Non renseigné',
d'ailleurs on va avoir un souci si non renseigné, on va pas savoir si faut dédoublonner ou pas

2023-05-04 10:11 UTC, squirrion commented on src/services/exports/exports.repository.ts
> +            contrat?.typeDeContrat ?? 'Non renseigné',
d'ailleurs on va avoir un souci si non renseigné, on va pas savoir si faut dédoublonner ou pas

2023-05-04 10:12 UTC, squirrion commented on src/services/misesEnRelation/controllers/getContrats.ts
> +      const statutOld = ['recrutee', 'nouvelle_rupture', 'renouvellement'];
renouvellement ? pareil je sais pas encore comment ca va se passer (j'au vu renouvelee plus haut)

2023-05-04 10:14 UTC, squirrion commented on src/services/misesEnRelation/controllers/getContrats.ts
> +      const totalConvention = await totalContrat(app, checkAccess, statutOld);
statutOld ?

2023-05-04 10:16 UTC, squirrion commented on src/services/misesEnRelation/controllers/getHistoriqueContrats.ts
> +            (totalParStatut) => totalParStatut.statut === 'renouvelee', // statut à définir pour le renouvellement de contrat
oui ca va dépendre de la partie de Moustapha si nouveau statut impact un peu partout (espace SA, api originel etc)
Il me semblait qu'il avait un flag si CDI renouvellé et doublonnage si CDD (l'ancien contrat serait en fin de contrat naturel) mais à confirmer...

2023-05-10 09:43 UTC, squirrion commented on src/services/exports/controllers/getExportHistoriqueContratsCsv.ts
> +                  dateRecrutement: { $gte: dateDebut, $lte: dateFin },
si on a la date de début de contrat ?

2023-05-10 09:50 UTC, squirrion commented on src/services/exports/exports.repository.ts
> +            contrat?.typeDeContrat ?? 'Non renseigné',
Il va falloir qu'on statut ici on va avoir un souci

2023-05-10 09:52 UTC, squirrion requested changes
En attente de revue des autres PRs, gros impact avec nouveau statut (import coop / ruptures / espaces SA / exports etc)

2023-05-17 12:06 UTC, squirrion commented on src/services/exports/controllers/getExportHistoriqueContratsCsv.ts
> +                  'emetteurRenouvellement.date': {
il faut qu'on rajoute des index mongo je pense

2023-05-17 12:07 UTC, squirrion commented on src/services/exports/controllers/getExportHistoriqueContratsCsv.ts
> +                  dateRecrutement: { $gte: dateDebut, $lte: dateFin },
ok normal ? je crois qu'on a quelques cas à null en prod avant l'obligation de la date previsionnelle obligatoire

2023-05-17 12:07 UTC, squirrion commented on src/services/exports/controllers/getExportHistoriqueContratsCsv.ts
> +              emetteurRenouvellement: 1, // à définir
tu peux enlever le comm

2023-05-17 12:08 UTC, squirrion commented on src/services/misesEnRelation/controllers/getHistoriqueContrats.ts
> +              dateRecrutement: { $gte: dateDebut, $lte: dateFin },
index mongo

2023-05-17 12:10 UTC, squirrion commented on src/services/misesEnRelation/misesEnRelation.repository.ts
> +      $in: ['finalisee', 'finalisee_rupture'],
nouvelle_rupture ?

2023-05-17 12:10 UTC, squirrion commented on src/services/misesEnRelation/misesEnRelation.repository.ts
> +          $in: ['finalisee_rupture', 'finalisee'],
nouvelle_rupture ?

2023-05-22 08:36 UTC, QuentinFontenay commented on src/services/misesEnRelation/misesEnRelation.repository.ts
> +      $in: ['finalisee', 'finalisee_rupture'],
non pour l'historique du coup c'est les ruptures validées

2023-05-26 10:44 UTC, merged