désactivation invite administrateur si structure inactive
anct-cnum/api-admin-conseillers-numerique pull request #281
Opened 2023-09-26 13:53 UTC by dienamo

2023-09-26 15:16 UTC, squirrion commented on src/services/users/controllers/postInvitationStructure.ts
> +    if (StatutsStructuresInactives.includes(structure.statut)) {
ok à voir , je crois que dans d'autres controllers, on faisait direct un check statut VALIDATION_COSELEC (à vérifier)

2023-09-27 16:13 UTC, dienamo commented on src/utils/index.ts
> +          ~~b.numero?.replace('COSELEC ', '')
oui au début c'est undefined et ça bug

2023-09-28 09:39 UTC, squirrion approved these changes

2023-09-28 10:00 UTC, QuentinFontenay commented on src/services/users/controllers/postInvitationStructure.ts
> +      .accessibleBy(req.ability, action.read)
```suggestion
     .Model.accessibleBy(req.ability, action.read)
```

2023-09-28 10:03 UTC, QuentinFontenay requested changes
commentaire

2023-09-28 10:05 UTC, QuentinFontenay commented on src/ts/enum.ts
> +const StatutsStructuresActives = ['VALIDATION_COSELEC'];
pourquoi tu filtres pas directement dans la requête par le statut VALIDATION_COSELEC

2023-09-28 10:07 UTC, dienamo commented on src/ts/enum.ts
> +const StatutsStructuresActives = ['VALIDATION_COSELEC'];
c'est pour plus tard si on a d'autres cas de structures actives? cc @squirrion

2023-09-28 10:21 UTC, squirrion commented on src/services/users/controllers/postInvitationStructure.ts
> +     .Model.accessibleBy(req.ability, action.read)
lint

2023-09-28 10:23 UTC, squirrion commented on src/ts/enum.ts
> +const StatutsStructuresActives = ['VALIDATION_COSELEC'];
on peut effectivement mettre en dur 'VALIDATION_COSELEC' dans le controller souhaité comme c'est ce que l'on a dans les autres. On passera en enum ici le jour où on gérera un nouveau statut actif

2023-09-28 12:15 UTC, squirrion approved these changes

2023-09-28 12:16 UTC, QuentinFontenay approved these changes

2023-09-28 12:16 UTC, merged