Ajout des mises en relation à archiver
anct-cnum/api-admin-conseillers-numerique pull request #432
Opened 2024-01-24 11:40 UTC by MorganP-projects

2024-01-24 11:45 UTC, Ornella452 approved these changes

2024-01-25 08:01 UTC, squirrion commented on src/services/conseillers/controllers/deleteCandidatById.ts
> +      const instructionSuppressionMER =
Mêmes remarques que côté ancien api (nbDoublonsReel / match coupé / champs dans le project)

2024-01-25 08:02 UTC, squirrion commented on src/services/conseillers/controllers/deleteCandidatById.ts
> +              historiqueContrat: misesEnRelations,
```suggestion
              historiqueContrats: misesEnRelations,
```

2024-01-25 08:02 UTC, squirrion commented on src/services/conseillers/controllers/deleteCandidatById.ts
>                motif,
Il faudra ajuster le modele et l'interface ?

2024-01-25 14:59 UTC, squirrion requested changes
Retours PR

2024-01-30 14:07 UTC, squirrion commented on src/services/conseillers/controllers/deleteCandidatById.ts
> +              historiqueContrats: misesEnRelations,
même remarque que dans l'ancien api : on fait un foreach pour chaque doublon mais on peut le même OBj dans  historiqueContrats ?

2024-01-30 14:08 UTC, squirrion commented on src/services/conseillers/controllers/deleteCandidatById.ts
> +          conventionnement: 1,
ca n'existe pas non ?

2024-01-30 14:11 UTC, squirrion commented on src/services/conseillers/controllers/deleteCandidatById.ts
> +          conventionnement: 1,
Manque miseEnRelationConventionnement & miseEnRelationReconventionnement

2024-02-01 17:19 UTC, squirrion commented on src/services/conseillers/controllers/deleteCandidatById.ts
> +                (mer) => mer.id !== conseiller._id,
même remarque que sur l'ancien api - ce serait pas plutôt un genre de String(mer.conseiller.oid) === String(conseiller._id)

2024-02-06 12:44 UTC, QuentinFontenay commented on src/models/conseillersSupprimes.model.ts
> +      historiqueContrats: { type: [Object] },
il faut que tu crées un schéma comme par exemple:
`
const contactSchema = new Schema(
    {
      prenom: String,
      nom: String,
      fonction: String,
      email: String,
      telephone: String,
    },
    { _id: false, strict: false },
  );
`

2024-02-06 12:44 UTC, QuentinFontenay commented on src/models/conseillersSupprimes.model.ts
> +      historiqueContrats: { type: [Object] },
tu as pas mal d'exemple dans le model structure

2024-02-06 12:45 UTC, QuentinFontenay commented on src/services/conseillers/controllers/deleteCandidatById.ts
> +                (mer) => String(mer.conseiller.$id) === String(conseiller._id),
```suggestion
                (misesEnRelation) => String(misesEnRelation.conseiller.$id) === String(conseiller._id),
```

2024-02-06 15:21 UTC, Ornella452 commented on src/services/conseillers/controllers/deleteCandidatById.ts
> +                (misesEnRelation) => String(misesEnRelation.conseiller.$id) === String(conseiller._id),
petit lint

2024-02-06 16:08 UTC, MorganP-projects commented on src/services/conseillers/controllers/deleteCandidatById.ts
> +                (misesEnRelation) => String(misesEnRelation.conseiller.$id) === String(conseiller._id),
yes ça vient de l'ajout direct de la correction de wording

2024-02-07 14:06 UTC, QuentinFontenay commented on src/services/conseillers/controllers/deleteCandidatById.ts
> +            $match: instructionSuppressionMER,
access control

2024-02-12 17:29 UTC, squirrion submitted a review, later dismissed

2024-02-12 17:52 UTC, QuentinFontenay commented on src/services/conseillers/controllers/deleteCandidatById.ts
> +          { $match: checkAccessMiseEnRelation },
c'est pas bon il faut faire un seul $match

2024-02-12 17:52 UTC, squirrion commented on src/services/conseillers/controllers/deleteCandidatById.ts
> +                (misesEnRelation) =>
```suggestion
                (miseEnRelation) =>
```

2024-02-12 17:53 UTC, QuentinFontenay commented on src/services/conseillers/controllers/deleteCandidatById.ts
> +          { $match: checkAccessMiseEnRelation },
`$match: {
$and: [checkAccessMiseEnRelation],
... instructionSuppressionMER
}`

2024-02-12 17:53 UTC, QuentinFontenay commented on src/services/conseillers/controllers/deleteCandidatById.ts
> +          { $match: checkAccessMiseEnRelation },
quelque chose comme ça

2024-02-14 09:32 UTC, squirrion approved these changes

2024-02-14 09:43 UTC, QuentinFontenay approved these changes

2024-02-14 10:20 UTC, merged